### ISSUE TITLE
Set signal state

### ISSUE THREAD

**Issue by vishalak** [vishalak/TsmManager#10]
Change the state of a specified signal to change the status of any phase to green, yellow, red.

**Comment by vishalak** [comment]
Signals are by approach. I have added a feature to set any traffic signal's specified movement state to Red, Yellow, or Green.

![image](https://user-images.githubusercontent.com/7433272/111356374-af3d2580-865e-11eb-9625-42086e93d6e6.png)

**Comment by vishalak** [comment]
@realzyc 
Could you please test this feature and let me know if it works? Thanks.

**Comment by realzyc** [comment]
Great! Will do

**Comment by realzyc** [comment]
Hi @vishalak, we are trying to verify this part but it seems that the activation code don't work.

Check this:

![image](https://user-images.githubusercontent.com/5388933/112134861-1f701c00-8c08-11eb-8d8b-cf7e9d694219.png)

Does it mean the code expires? Thanks for help.

**Comment by realzyc** [comment]
Besides, I have a detailed question about Signal. It seems that we may have different idea of signal.

For example, in VISSIM we have SignalController (SC) for each intersection, which stands for all signal head and movement for a intersection. And in each SC there are SignalGroup(SG), which stands for the color of the signal head (heads).

As the result, I might get 4 SC (ID from 0 to 3) for 4 intersection, in each SC there are about 8 SG (ID from 1 to 8). then I can set the signal status like:
`SC[ID=0].SG[ID=1].Color = 'RED'`.

Do we have a similar concept in TransModler? 

From your screenshot the ID of Signal is 302 which means we have 300+ intersections in the network? And it seems that the movement "T", "L" is for a single direction, what if I want to set the status for each direction, each movement of a given intersection? say

`Intersection[ID = 0].SG[ID = 3].Color = 'Red'` (this is better), OR
`Intersection[ID = 0].Direction[ID = 3].Movement['T].Color = 'Red'`.

**Comment by vishalak** [comment]
If you choose "I want to activate the software" does it not work? Please email me your serial number at my Caliper email address and I'll check internally if your license has expired.

Currently, you can get a signal for each approach of an intersection by using the signal id from the TransModeler API and for that signal, you can set any of its movement's color. For example,

![image](https://user-images.githubusercontent.com/7433272/112225203-cea9f480-8c02-11eb-9e72-d5c059ee1ca7.png)

For doing this without modifying the existing API, you could create a local array of signals for each intersection within your app and then set their state. Please let me know if this is not clear and I'd be happy to provide more details.

**Comment by realzyc** [comment]
Hi @vishalak thanks for your feedback and it's good enough for now.

This feature is verified.

![image](https://user-images.githubusercontent.com/5388933/112566037-35086000-8e19-11eb-9a15-3c198c6da474.png)

**Comment by vishalak** [comment]
Sounds good, thank you @realzyc
