### ISSUE TITLE
Get the location of the center of given intersection 

### ISSUE THREAD

**Issue by realzyc** [vishalak/TsmManager#11]
Hi @vishalak, in addition to #8, we need a way to get the location(x and y, or longitude and latitude) of a given point in the map.

The reason is we need to know the location of the very center of those intersections, and we know the location of vehicle, so that we know the relationship of intersection and vehicle in PASS.

So we want the center location of intersection, in addtion to location of vehicle (in #8 ).

To make it easy, the possible solution is
1) enable us to put a sign, or mark, or something in the map (center of the intersection), which will not impact the traffic.
2) allow TsmManager to get the location of sign by given id.

Please let me know if it's possible.

**Comment by vishalak** [comment]
@realzyc Sorry about the delay in my response to this question. I have been busy with a high-priority project. I'll see what we can do about this and let you know soon.

**Comment by vishalak** [comment]
All Nodes in TransModeler have a position so you could do this directly from the Nodes layer in TransModeler.

If you are still interested in adding custom signs or markers, you could add a new point layer by going to File > New > Geographic File and create a new Point Layer. Once the point layer is created, you can add points anywhere in the network and get their coordinates by using the GetPoint(id) GISDK function. I hope this helps.

**Comment by realzyc** [comment]
Thanks for your reply, tried Netork.Nodes in API but cannot find the position related property, please let me know if it's the one you mentioned as Nodes layer.

![image](https://user-images.githubusercontent.com/5388933/115979582-5778cf00-a5b9-11eb-9c08-cc370bcfba6c.png)

**Comment by vishalak** [comment]
@realzyc Actually, I meant setting the layer to Nodes layer and getting the coordinates. Please see the sample code below. I have also added it to GetVehicleInformation() method for now so you could see it in the code.

![image](https://user-images.githubusercontent.com/7433272/116106495-27483380-a680-11eb-8b84-4895a827ffba.png)
