### ISSUE TITLE
Run single step

### ISSUE THREAD

**Issue by vishalak** [vishalak/TsmManager#4]
Advance the simulation by a single step

**Comment by vishalak** [comment]
Implemented. First click the Step Mode button, specify the step size in seconds in the text box below it, and click the Step Forward button to advance simulation by a single step of specified step size.

**Comment by realzyc** [comment]
Failed:

Environment
```
TransModeler License (SW)
Version 6.0 Build 8055 64-bit

Win10 Pro 
Version 1909
OS build 18363.1316

Visual Studio 2017
Version 15.9.2

.Net Framework 4.6.1
Version 4.8.03752
```

Test Case 1:
----------
- Click Start button to start simulation
- Click Stop button to stop simulation
- Click Start button to restart simulation
- Click Stop button to stop simulation
- Success

Test Case 2:
----------
- Click Start button to start simulation
- Click step mode button: success, the staus of enter step mode is True

![image](https://user-images.githubusercontent.com/5388933/105468185-a882d980-5cd1-11eb-843e-b70254aec093.png)

- Keep the step size "1" unchanged, click the Step Forward button: * Nothing happened *, the simulation don't move and no popup message or error message.

- Keep clicking the Step Forward button but nothing happened: The simulation keep stopping.

![image](https://user-images.githubusercontent.com/5388933/105468498-031c3580-5cd2-11eb-8bb1-277679abc730.png)

- Click Stop button to stop simulation

Success message popup but the simulation is still not cleaned or moved.

![image](https://user-images.githubusercontent.com/5388933/105468583-1c24e680-5cd2-11eb-8f73-38b6d0edbd14.png)

- Click Start button, success message popup but the simulation is still not moved.

![image](https://user-images.githubusercontent.com/5388933/105468692-38288800-5cd2-11eb-85fc-6c9e7551b7bf.png)


@vishalak please take a look when you have time. Thanks for your help.

**Comment by vishalak** [comment]
There was a minor tweak needed in the API to allow advancing by a step. I implemented it in the development version. It needs to be migrated to the release version and you will need the updated version of TransModeler to test this feature. 

We will send a link to the updated version of TransModeler soon.

**Comment by realzyc** [comment]
Verified with `TransModeler License (SW) Version 6.0 Build 8080 64-bit`.

Thanks @vishalak

**Comment by vishalak** [comment]
Thanks for testing and verifying this feature @realzyc 

I will work on the remaining few feature requests soon. You can track the progress here on Github. Please email me if you have any questions.
