### ISSUE TITLE
Get vehicle status

### ISSUE THREAD

**Issue by vishalak** [vishalak/TsmManager#8]
Get all current vehicles in the network with their type, location, speed, heading, etc.

**Comment by vishalak** [comment]
@realzyc
Just for clarity, could you please describe what would you like from this feature? Please confirm if you want the status of _all vehicles_ in the network at once (like a snapshot of all vehicles at any given time). If the network is large this could take time.

**Comment by realzyc** [comment]
Hi @vishalak, please check this:

- similar with get detector status, we want to get vehicle status before or after each single step.
- Ideally we want all vehicles in the network at once, if they are running in the network.
- If it takes time to generate that data, in fact, we only need the vehicles with given vehicle types. for example, we can setup several types of vehicle, which only run in a given route, then in PASS we want to keep collecting the trajactories of those vehicles.

**Comment by vishalak** [comment]
@realzyc 

TransModeler has built-in functionality to output vehicle trajectories. Could you please take a look and let me know if the existing functionality works for you? It will be much faster to get the trajectories directly out of TransModeler instead of the out-of-process app.

To turn on the collection of vehicle trajectories, you can go to Project > Settings > Output tab and check the Vehicle Trajectories checkbox, and then on the Options tab select one of the supported trajectory formats before beginning the simulation run.
![image](https://user-images.githubusercontent.com/7433272/114222372-86960c00-993c-11eb-994d-a54a640ed2f9.png)
![image](https://user-images.githubusercontent.com/7433272/114222727-ebe9fd00-993c-11eb-8c5d-335ab5d982aa.png)

**Comment by realzyc** [comment]
Thanks for your reply. Yes getting trajectory from file I/O is a possible solution. We used to use file I/O but find issues: Since we need the real-time location during each single step, PASS needs to read file after each single step of TransModeller, which will slow down the simulation and make the real time simulation unavailable.

So use TranModeller to output trajectory to file is not a possible solution in this case.

**Comment by vishalak** [comment]
@realzyc  Just to confirm, you are interested in only a type or class of vehicles and their position at every time step to be available in memory (not through a file). Is that correct?

**Comment by vishalak** [comment]
@realzyc This is very doable, please refer to the GetVehicleInformation() method in the Manager.cs file. You can get a list of vehicles at any given point from the Network interface and look for properties of interest for each vehicle.

To see the ITsmVehicle interface refer to Help > TransModeler API Help > Network Interface > Vehicles and let me know if you have any additional questions.

**Comment by realzyc** [comment]
The GetVehicleInformation() method is exactly what we want!

By checking the ITsmVehicle interface, we need the ITsmVehicle.Center to get the vehicle location

```
// Longitude, latitude, and altitude of the vehicle

HRESULT Center([out, retval] STsmCoord3* pVal);
```

However, we failed to get this property when runing the demo.

```
var location = v.Center;
```
![image](https://user-images.githubusercontent.com/5388933/115978877-11217100-a5b5-11eb-8096-1cc534d63063.png)


The error message is: 
'v.Center' threw an exception of type 'System.ArgumentException'
"Value does not fall within the expected range."

**Comment by vishalak** [comment]
@realzyc Maybe you could use the same approach for this as I mentioned in #11 

![image](https://user-images.githubusercontent.com/7433272/116109217-958df580-a682-11eb-833a-43491a2d17db.png)

I tested this and it seems to be working well.

![image](https://user-images.githubusercontent.com/7433272/116109387-b6564b00-a682-11eb-863c-3f144738f003.png)
