### ISSUE TITLE
Get detector status

### ISSUE THREAD

**Issue by vishalak** [vishalak/TsmManager#9]
Get status of all detectors in the network

**Comment by vishalak** [comment]
@realzyc for this feature, would you like the status of the detectors/sensors to be output to a CSV file? Also, which attributes of the detectors are you interested in?
Here are some of the available properties for detectors - ID, Flow, Speed, Occupancy, Headway, LastActuationTime, IsActivated, IsOccupied, etc.

**Comment by realzyc** [comment]
@vishalak For this feature, I'd like the status of detectors to be output by build in function, not to file.

It's because we need to call this function after each single step, real-time.

The status I need is just whether the detector is detected or not, or in a word, if a detector call should be sent to signal controller.

So I would like the function like:

```
/// <summary>
/// Check and get if there's a detector call for a given phase of a given signal. call after each single step.
/// </summary>
/// <param name="signalId">The signal id in TransModeler</param>
/// <param name="phaseId">The phase id of that given signal</param>
bool GetDetectorCall(string signalId, string phaseId);
```

It's also ok if I can get all detectors status by one call.

**Comment by vishalak** [comment]
@realzyc
To do this without modifying the existing API, we could use the IsActivated property of detectors (referred to as sensors in TSM). Since detectors are on lanes and we would know which detector id corresponds with which phase/movement for a signal, we could simplify the method to just take the detector id as an input argument and return a boolean status of whether it is activated or not.

bool IsSensorActivated(int sensorId);

Would this work for you?

For example, in the screenshot below sensor id 1376 (blue rectangle with " i " on it) corresponds with the left movement and is not activated.
![image](https://user-images.githubusercontent.com/7433272/111478592-99833b00-8706-11eb-91c6-2f515b303edc.png)

**Comment by realzyc** [comment]
Yeah, @vishalak , I think this works for me.

**Comment by vishalak** [comment]
@realzyc I have implemented the functionality to get and set detector status in the latest update. Please test and let me know if it works ok for you so we can close this case.

Please note that the output detector information and vehicle information buttons are still a work in progress.

**Comment by realzyc** [comment]
![image](https://user-images.githubusercontent.com/5388933/114117949-563d7600-991a-11eb-8284-95affc84d6f6.png)

@vishalak thanks for your help and it works!

**Comment by vishalak** [comment]
Thanks for testing and confirming. I'll close this case.
